export const LOGIN_SUCCESS = "USERS_LOGIN_SUCCESS";

export const LOGOUT = "USERS_LOGOUT";

export const WORD_SUCCESS = "WORD_SUCCESS";
export const GAME_RESTART = "GAME_RESTART";

export const REGISTER_SUCCESS = "USERS_REGISTER_SUCCESS";
export const REGISTER_FAILURE = "USERS_REGISTER_FAILURE";

export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";
